
set -g prefix C-Space
unbind C-b
bind C-Space send-prefix

set -g default-terminal "xterm-256color"
set -g status-position top
set -g status-justify centre
set -g status-left-length 50
set -g status-right-length 150

# Nerd Font Icons & Styling
set -g status-style "fg=#7aa2f7,bg=#1f2335"

set -g status-left "#[fg=#15161e,bg=#7aa2f7,bold]  #S #[fg=#7aa2f7,bg=#1f2335,nobold] |"

set -g status-right "#[fg=#7aa2f7,bg=#1f2335] 󰁹 #(termux-battery-status | jq .percentage)%% |  %l:%M %P "

setw -g window-status-activity-style "underscore,fg=#a9b1d6,bg=#1f2335"
setw -g window-status-separator " | "
setw -g window-status-style "NONE,fg=#a9b1d6,bg=#1f2335"
setw -g window-status-format "#I #W"
setw -g window-status-current-format "#[fg=#7aa2f7,bg=#3b4261,bold] #I #W "

set -g base-index 1
set -g pane-base-index 1
set -g mouse on
set -sg escape-time 0
set -g display-panes-time 2500
set -g renumber-windows on
set -sa terminal-overrides ",xterm*:Tc"

set -g @tpm_plugins '              \
  tmux-plugins/tpm                 \
  tmux-plugins/tmux-sensible       \
  tmux-plugins/tmux-yank           \
  tmux-plugins/tmux-pain-control   \
  tmux-plugins/tmux-copycat        \
  tmux-plugins/tmux-sessionist     \
  jabirali/tmux-tilish             \
  sunaku/tmux-navigate             \
  tmux-plugins/tmux-resurrect      \
  tmux-plugins/tmux-continuum      \
  sainnhe/tmux-fzf                 \
'

# Install `tpm` if needed.
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

run '~/.tmux/plugins/tpm/tpm'

# Plugin options.
set -g @tilish-navigate 'on'
set -g @tilish-default 'main-vertical'
set -g @tilish-dmenu 'on'
set -g @resurrect-strategy-nvim 'session'
set -g @contimuum-restore 'on'
set -g @continuum-boot 'on'

unbind [
unbind p

# Key bindings
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

bind Escape copy-mode
bind-key R source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded"

bind-key p paste-buffer
bind-key a "detach-client -a"
bind-key K "kill-session"

bind-key t display-popup -E -d '#{pane_current_path}' -w 85% -h 85% fish
bind-key y display-popup -E -d '#{pane_current_path}' -w 85% -h 85% yazi
bind-key g display-popup -E -d '#{pane_current_path}' -w 85% -h 85% lazygit

bind-key -n F2 source-file ~/.tmux.conf \; display-message "tmux.conf reloaded."
bind-key -n C-F11 set -g status
